import Header from "../components/header/Header"

import { Source_Sans_3 } from "next/font/google"
import "./globals.css"
import Footer from "@/components/footer/Footer"
import { Suspense } from "react"
import Loading from "./loading"

const sourceSans = Source_Sans_3({ subsets: ["latin"] })

export const metadata = {
  title: "The Movie Database (TMDB)",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sourceSans.className}>
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  )
}
